### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bbhtt**
I only wanted to bump the runtime version to 20.08 -> 21.08 and the dependencies, turned out to be a lot more than that.

Changes:

- Switch to `libcanberra` from the shared-module and add it as a submodule
- `valac` was being required to build `gsound` which isn't present in the FDO runtime, so it is disabled.
- `gsound` was updated to `1.0.3` and buildsystem was switched to `meson` as `gsound` dropped `autotools` support: https://gitlab.gnome.org/GNOME/gsound/-/commit/463f4fa6a17d66fe664cd89dbc1a0863cb582ec4
- Update `graphene` to `1.10.8` and `gthree` to `0.9.0`

- `gnome-hexgl` had to be switched to git master as building on the 0.2.0 tag was failing with missing `gtk.h` and `gdk-pixbuf.h`. Those two are present in the SDK so not sure why it'd fail, but master works. If anyone can figure it out I will gladly revert it.

```
The Meson build system
Version: 0.59.4
Source dir: /run/build/gnome-hexgl
Build dir: /run/build/gnome-hexgl/_flatpak_build
Build type: native build
Project name: gnome-hexgl
Project version: 0.2.0
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency gthree-1.0 found: YES 1.0
Run-time dependency gsound found: YES 1.0.3
Library m found: YES
WARNING: Project targeting '>= 0.48.0' but tried to use feature introduced in '0.49.0': configure_file.configuration dictionary.
Configuring wrapper.sh using configuration
Build targets in project: 1
WARNING: Project specifies a minimum meson_version '>= 0.48.0' but uses features which were added in newer versions:
 * 0.49.0: {'configure_file.configuration dictionary'}

Found ninja-1.10.2 at /usr/bin/ninja
[1/12] Compiling C object gnome-hexgl.p/src_hexgl.c.o
FAILED: gnome-hexgl.p/src_hexgl.c.o 
ccache cc -Ignome-hexgl.p -I. -I.. -I/app/include/gthree-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-4 -I/app/include/graphene-1.0 -I/app/lib/graphene-1.0/include -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g '-DDATADIR="/app/share/gnome-hexgl"' -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -pthread -D_REENTRANT -mfpmath=sse -msse -msse2 -MD -MQ gnome-hexgl.p/src_hexgl.c.o -MF gnome-hexgl.p/src_hexgl.c.o.d -o gnome-hexgl.p/src_hexgl.c.o -c ../src/hexgl.c
../src/hexgl.c:2:10: fatal error: gtk/gtk.h: No such file or directory
    2 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/12] Compiling C object gnome-hexgl.p/src_utils.c.o
FAILED: gnome-hexgl.p/src_utils.c.o 
ccache cc -Ignome-hexgl.p -I. -I.. -I/app/include/gthree-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-4 -I/app/include/graphene-1.0 -I/app/lib/graphene-1.0/include -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g '-DDATADIR="/app/share/gnome-hexgl"' -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -pthread -D_REENTRANT -mfpmath=sse -msse -msse2 -MD -MQ gnome-hexgl.p/src_utils.c.o -MF gnome-hexgl.p/src_utils.c.o.d -o gnome-hexgl.p/src_utils.c.o -c ../src/utils.c
In file included from /app/include/gthree-1.0/gthree/gthreeuniforms.h:8,
                 from /app/include/gthree-1.0/gthree/gthreeshader.h:7,
                 from /app/include/gthree-1.0/gthree/gthreeprogram.h:8,
                 from /app/include/gthree-1.0/gthree/gthreematerial.h:10,
                 from /app/include/gthree-1.0/gthree/gthreemeshmaterial.h:8,
                 from /app/include/gthree-1.0/gthree/gthree.h:11,
                 from ../src/utils.h:1,
                 from ../src/utils.c:1:
/app/include/gthree-1.0/gthree/gthreetexture.h:9:10: fatal error: gdk-pixbuf/gdk-pixbuf.h: No such file or directory
    9 | #include <gdk-pixbuf/gdk-pixbuf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Error: module gnome-hexgl: Child process exited with code 1
```

-  The screenshots in the appdata are 404-ing https://people.gnome.org/~alexl/gnome-hexgl-2.png, https://people.gnome.org/~alexl/gnome-hexgl-1.png. I couldn't find "official" screenshots anywhere, so I included mine. If this is fine, then the screenshots must be added to this repo beforehand, otherwise the appstream validation will fail. I can split that out if required. Else if there is an "official" screenshot somewhere, I can add that as well.

Seems to run fine from my testing.

cc @alexlarsson

### CODE REVIEW

File: org.gnome.HexGL.json [hunk 1]
```diff
@@ -61,7 +48,7 @@
                 {
                     "type" : "git",
                     "url" : "https://github.com/ebassi/graphene",
-                    "tag" : "1.10.0"
+                    "tag" : "1.10.8"
```
Comment (hfiguiere) [inline org.gnome.HexGL.json:53]: Graphene is in the GNOME runtime.

**Review by hfiguiere — CHANGES_REQUESTED** [review]

**Comment by hfiguiere** [comment]
for gsound I'm sure you could just disable vala.

File: org.gnome.HexGL.json (hunk 1 above)
Comment (bbhtt) [reply org.gnome.HexGL.json:53]: Huh, I didn't see this when building. Thanks.

**Comment by bbhtt** [comment]
> for gsound I'm sure you could just disable vala.

I didn't check for this, but now when I checked,  indeed there is a meson flag. But what would be better - using the GNOME runtime or bundling graphene and using the Freedesktop runtime?

**Comment by hfiguiere** [comment]
the freedesktop runtime is smaller.

**Comment by bbhtt** [comment]
> the freedesktop runtime is smaller.

Ok, I reverted back to the FDO runtime. Thanks.

File: org.gnome.HexGL.json [hunk 2]
```diff
@@ -85,8 +74,11 @@
             "sources" : [
                 {
                     "type" : "git",
-                    "url" : "https://github.com/alexlarsson/gnome-hexgl",
-                    "tag" : "0.2.0"
+                    "url" : "https://github.com/alexlarsson/gnome-hexgl.git"
```
Comment (hfiguiere) [inline org.gnome.HexGL.json]: you need an explicit revision.

Comment (bbhtt) [reply org.gnome.HexGL.json]: 0.2.0 is the latest but that doesn't build I pasted the logs in the first post. Any idea?

Comment (bbhtt) [reply org.gnome.HexGL.json]: Oh, I misread revision as version...

Comment (hfiguiere) [reply org.gnome.HexGL.json]: did you file a bug about not building? Also you updated a depenency with what I think, according to the version number, might be an incompatible revision.

Comment (bbhtt) [reply org.gnome.HexGL.json]: The error looks weird and unrelated to the dependencies, I can open a bug for it. But yes I think with gthree 0.9.0 we need master of hexgl as it is split into gtk3 https://github.com/alexlarsson/gnome-hexgl/commit/edf6a7592ce1cab6b936b0dfb8c780d3fe710d3e but this hasn't made into a release.

Comment (hfiguiere) [reply org.gnome.HexGL.json]: if the ghtree update cause this then it should be held back.

Comment (bbhtt) [reply org.gnome.HexGL.json]: It looks unrelated to gthree, it can't find the headers `./src/hexgl.c:2:10: fatal error: gtk/gtk.h: No such file or directory`, but these are present which is weird.

Comment (bbhtt) [reply org.gnome.HexGL.json]: Ok I opened an issue about the build failure and specified a commit which works fine.

Comment (hfiguiere) [reply org.gnome.HexGL.json]: so hexgl 0.2.0 build with gthree 0.2.0.

As I said, sometime you should just hold back upgrading things.

Comment (hfiguiere) [reply org.gnome.HexGL.json]: See #3.

Comment (bbhtt) [reply org.gnome.HexGL.json]: Yea, I realized that later when I opened the issue for HexGL. The error was throwing me off. Thanks.

**Comment by bbhtt** [comment]
Closing in favour of https://github.com/flathub/org.gnome.HexGL/pull/3
